# Site settings
title: "Josh Pell'Blog"
email: joshpell@163.com
description: "When you think you can stop learning, is a time when you are going to be washed out."
baseurl: ""
url: "https://joshpelltan.github.io"
title_description: "I’m a software engineer lived in Beijing China. This is my very own blog which shares skills. All written content on this site is provided under a Creative Commons ShareAlike license and all code is provided under a MIT license unless otherwise stated. Please give source if you'd like to quote.If you have any questions, please contact me."
title_image: "http://pic.yupoo.com/joshpell/G4M7oUg0/MSOIW.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/JoshPellTan
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  JoshPellTan
instagram_username: 
reddit_username: 
linkedin_link: http://www.linkedin.com/in/健-谭-811428109?trk=hp-identity-name
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"tencent://message/?uin=462989817&Site=&Menu=yes\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/JoshPellTan/JoshPellTan.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
